spring:
  application:
    name: programmers spring assignments
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: "jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql

jwt:
  token:
    header: Authentication
    issuer: sohyounsoo
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0